version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: toy
      MYSQL_USER: yulin
      MYSQL_PASSWORD: 12345678
    ports:
      - "8080:8080"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: